### ISSUE TITLE
IntegrityError

### ISSUE THREAD

**Issue by evyatarc** [jarondl/pygtfs#14]
Would you mind helping me with the error below when I try to look at MTA subway data? The link to the GTFS data is https://datamine-history.s3.amazonaws.com/gtfs-2014-09-17-09-31

IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: shapes.feed_id, shapes.shape_id [SQL: 'INSERT INTO shapes (feed_id, shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence, shape_dist_traveled) VALUES (?, ?, ?, ?, ?, ?)'] [parameters: ((1, '4..N06R', 40.668897, -73.932942, '0', None), (1, '4..N06R', 40.669399, -73.942161, '1', None), (1, '4..N06R', 40.669847, -73.950466, '2', None), (1, '4..N06R', 40.669922, -73.951706, '3', None), (1, '4..N06R', 40.670083, -73.954713, '4', None), (1, '4..N06R', 40.670096, -73.954983, '5', None), (1, '4..N06R', 40.670118, -73.955258, '6', None), (1, '4..N06R', 40.670157, -73.955542, '7', None)  ... displaying 10 of 5001 total bound parameter sets ...  (1, 'L..S01R', 40.683552, -73.905577, '260', None), (1, 'L..S01R', 40.683429, -73.905534, '261', None))]

**Comment by jarondl** [comment]
What is the format of the data?

    $ file gtfs-2014-09-17-09-31 
    gtfs-2014-09-17-09-31: data

**Comment by evyatarc** [comment]
It was downloaded as a zip file and loaded into the database as a folder with .txt files. 

For now I had to change one line of code in gtfs_entities.py; 

line 360: in class ShapePoint(Base):
    shape_pt_sequence = Column(Integer)

becomes 
    shape_pt_sequence = Column(Integer, primary_key=True)  # mjc 20160226: need a triple primary key here

Thus, the triple (feed_id, shape_id, shape_pt_sequence_id) is unique if you have multiple feeds and the data now loads.

**Comment by jarondl** [comment]
Yeah, that seems like a bug. Even the example in the specs https://developers.google.com/transit/gtfs/reference#shapestxt has multiple rows with the same shape_id.
That's a very quick one-line solution. Do you want to submit a pull-request, or should I fix it?

**Comment by evyatarc** [comment]
I will submit a pull-request. Thank you!

**Comment by jarondl** [comment]
Closed by #15
