### ISSUE TITLE
Looking at Stop Times by ID

### ISSUE THREAD

**Issue by evyatarc** [jarondl/pygtfs#16]
Is there a way to look at stop_times through a function like: stop_times_by_id()? Ex. - I want to answer a question like what are the stop times for the 33rd street stop? 

Looking through schedule.py - Is there an issue since stop_times has an underscore or is already plural while the other objects are singular and one word?

For now I am just running a basic loop in Python. Continuing with the earlier example, I am gathering every stop_times object with a stop_id that is equivalent to stops_by_id(33). I hope to hear your thoughts. Thank you in advance!

**Comment by elad661** [comment]
It works just as you'd expect:

```python
sched.stops_by_id(33)[0].stop_times
```
this will return a list of StopTime objects for a stop with the internal ID of 33.

**Comment by jarondl** [comment]
Quite right, @elad661 .
Closing.
