### ISSUE TITLE
Modify Feed

### ISSUE THREAD

**Issue by spencerrecneps** [jarondl/pygtfs#2]
What are your thoughts about enabling modifications to an imported feed? For my purposes, it would be nice to issue a command like "delete(routes, route_id=24)" or "delete(stop_times, route_id=15") and have the relevant information removed. It would also be nice to have an interface for adding information.

If there's a more efficient way to accomplish this without writing custom code within pygtfs I'd love to hear about it.

**Comment by jarondl** [comment]
For now, let's say the official solution is to use stock sqlalchemy API.
