### ISSUE TITLE
SQLAlchemy warnings

### ISSUE THREAD

**Issue by ikonst** [jarondl/pygtfs#32]
The package should be re-tested with various SQLAlchemy versions and the BART dataset:
http://www.bart.gov/sites/default/files/docs/google_transit_20160328_v1.zip

SQLAlchemy 0.7.8 (the minimum version according to setup.py) crashes.
SQLAlchemy 0.9.0 works.
SQLAlchemy 1.0.6 (latest at time of writing) doesn't work anymore.

**Comment by jarondl** [comment]
Seems to work with SQLAlchemy 1.2.14
I will add more tests to check different versions.

**Comment by jarondl** [comment]
bart importing now works properly.
