### ISSUE TITLE
Publish pygtfs on pypi

### ISSUE THREAD

**Issue by andrey-git** [jarondl/pygtfs#35]
Could you publish this package on Pypi, so it can be fetched without specifying the github URL?

home-assistant/home-assistant#7069

**Comment by jarondl** [comment]
Do you mean something like https://pypi.python.org/pypi/pygtfs 
(on PyPI at least a year)?
Or are you requesting a new release?

**Comment by andrey-git** [comment]
Sorry, I missed it.
