### ISSUE TITLE
Location type should accept type '2'

### ISSUE THREAD

**Issue by code-grandma-code** [jarondl/pygtfs#36]
Within gtfs_entities.py this line should be updated...
`    _validate_location = _validate_int_choice([None, 0, 1], 'location_type')`

To
`    _validate_location = _validate_int_choice([None, 0, 1, 2], 'location_type')`

 The location_type field identifies whether this  stop ID represents a stop, station, or station entrance. If no location  type is specified, or the location_type is blank, stop IDs are treated  as stops. Stations may have different properties from stops when they  are represented on a map or used in trip planning.  The location type  field can have the following values: 

 0 or blank - Stop. A location where passengers board or disembark from a transit vehicle. |   |  
1 - Station. A physical structure or area that contains one or more stop. |   |  
**2 - Station Entrance/Exit. A location where  passengers can enter or exit a station from the street.** The stop entry  must also specify a parent_station value referencing the stop ID of the  parent station for the entrance.**

**Comment by jarondl** [comment]
That sounds right to me.
Care to submit a PR?

**Comment by jarondl** [comment]
Ehm, this was fixed even before it was reported, in 
e3a3ccd77a594242f2db17bbb78a34c730901c43
