### ISSUE TITLE
Load database from file?

### ISSUE THREAD

**Issue by sid-kap** [jarondl/pygtfs#37]
Is there a way to convert the GTFS feed to a database and cache it to a file, so that every time after that I can load it instantly, rather than doing the GTFS -> database conversion (which takes over a minute) each time?

**Comment by jarondl** [comment]
Yes, the gtfs2db command should do exactly that - it loads the gtfs and converts it to a sqllite file, which then loads very quickly.

It is installed as a separate command when you install pygtfs.

**Comment by sid-kap** [comment]
How do I use it? The documentation is not very detailed.
Is `gtfs2db append feed.zip feed.db` the correct usage for creating a new DB?

**Comment by jarondl** [comment]
Yes, exactly.
