### ISSUE TITLE
Publish latest version on PyPI?

### ISSUE THREAD

**Issue by robbiet480** [jarondl/pygtfs#39]
Hi @jarondl, would you mind publishing the latest available version to PyPi? It's been quite a while since the last one and there's been some significant changes since. Thanks in advance!

**Comment by jarondl** [comment]
Sure, I'll try to do that soon.

**Comment by jarondl** [comment]
Done, with release 0.1.4

**Comment by unsignedint** [comment]
Hi @jarondl maybe it is time for a new release? :)
