### ISSUE TITLE
DeclarativeMeta object got multiple values for keyword argument 'feed_id'

### ISSUE THREAD

**Issue by leepeterson** [jarondl/pygtfs#55]
First time using pygtfs, so apologies in advance if I've not yet caught onto a possibly obvious solution...

Using pygtfs 0.1.5 on Ubuntu 16.04 with SQLite 3.11.0, running `gtfs2db append carta-sc-us.zip feed.db` fails with `TypeError: DeclarativeMeta object got multiple values for keyword argument 'feed_id'` while writing FeedInfo.

Strange as there's only 1 instance of `feed_id` and its value is `213`.

Not quite sure where to go from here. Any advice is greatly appreciated.

<details>
<summary>feed_info.txt Output</summary>
<pre>
➜ cat carta-sc-us/feed_info.txt
feed_publisher_url,feed_publisher_name,feed_lang,feed_version,feed_license,feed_contact_email,feed_contact_url,feed_start_date,feed_end_date,feed_id
http://www.trilliumtransit.com,"Trillium Solutions, Inc.",en,UTC: 16-May-2019 17:24,,support+carta-sc-us@trilliumtransit.com,http://support.trilliumtransit.com,20190516,20200101,213
</pre>
</details>

<details>
<summary>Console Output</summary>
<pre>
➜ gtfs2db append carta-sc-us.zip feed.db
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.Agency'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.Stop'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.Transfer'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.Route'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.Fare'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.FareRule'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.ShapePoint'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.Service'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.ServiceException'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.Trip'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.Frequency'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.StopTime'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.FeedInfo'&gt;:
Loading GTFS data for &lt;class 'pygtfs.gtfs_entities.Translation'&gt;:
1 record read for &lt;class 'pygtfs.gtfs_entities.Agency'&gt;.
881 records read for &lt;class 'pygtfs.gtfs_entities.Stop'&gt;.
2 records read for &lt;class 'pygtfs.gtfs_entities.Transfer'&gt;.
26 records read for &lt;class 'pygtfs.gtfs_entities.Route'&gt;.
6 records read for &lt;class 'pygtfs.gtfs_entities.Fare'&gt;.
64 records read for &lt;class 'pygtfs.gtfs_entities.FareRule'&gt;.
....44472 records read for &lt;class 'pygtfs.gtfs_entities.ShapePoint'&gt;.
8 records read for &lt;class 'pygtfs.gtfs_entities.Service'&gt;.
53 records read for &lt;class 'pygtfs.gtfs_entities.ServiceException'&gt;.
2381 records read for &lt;class 'pygtfs.gtfs_entities.Trip'&gt;.
2381 records read for &lt;class 'pygtfs.gtfs_entities.Frequency'&gt;.
......60829 records read for &lt;class 'pygtfs.gtfs_entities.StopTime'&gt;.
Failure while writing FeedInfo(feed_publisher_url='http://www.trilliumtransit.com', feed_publisher_name='Trillium Solutions, Inc.', feed_lang='en', feed_version='UTC: 16-May-2019 17:24', feed_start_date='20190516', feed_end_date='20200101', feed_id='213')
Traceback (most recent call last):
  File "/usr/local/bin/gtfs2db", line 9, in &lt;module&gt;
    load_entry_point('pygtfs==0.1.6.dev22+gbbc2691', 'console_scripts', 'gtfs2db')()
  File "/usr/local/lib/python3.5/dist-packages/pygtfs-0.1.6.dev22+gbbc2691-py3.5.egg/pygtfs/gtfs2db.py", line 55, in main
    chunk_size=int(args['--chunk-size']))
  File "/usr/local/lib/python3.5/dist-packages/pygtfs-0.1.6.dev22+gbbc2691-py3.5.egg/pygtfs/loader.py", line 84, in append_feed
    instance = gtfs_class(feed_id=feed_id, **record._asdict())
TypeError: DeclarativeMeta object got multiple values for keyword argument 'feed_id'
</pre>
</details>

**Comment by jarondl** [comment]
That's.. interesting. Can you send me a link to the full feed?

In any case, pygtfs assumes that there will be no field called `feed_id`. It supplies its own version of `feed_id`. That stems from the fact that feed_id is nowhere to be found in the specs:
https://developers.google.com/transit/gtfs/reference/#feed_infotxt

However, the specs also say that readers should ignore fields they do not understand, which we definitely don't do in this particular case.
