### ISSUE TITLE
pygtfs does not support UTF-8 encoding

### ISSUE THREAD

**Issue by jonathangat** [jarondl/pygtfs#66]
```append_feed``` returns ```UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 107: invalid continuation byte```

**Comment by jarondl** [comment]
I agree with @jimbudarz that error actually says your file was not valid UTF-8.  Many GTFS users (including myself) use it on non-english UTF-8.

Without seeing the GTFS file in question it would be hard to diagnose. I'm closing this, but feel free to reopen if you can share the gtfs.
