### ISSUE TITLE
Publish 0.1.8 to pypi (and all future releases automatically)

### ISSUE THREAD

**Issue by jimbudarz** [jarondl/pygtfs#73]
@jarondl Let's add a github action to build and publish new releases to PyPI. It's straightforward, but I assume you set up a github secret to contain the API key to publish there.

It looks like this was previously done via Travis but the link there is broken.

**Comment by jarondl** [comment]
Good idea

**Comment by jarondl** [comment]
Yay it worked with 0.1.9!
And no secrets needed! https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
