### ISSUE TITLE
include requirements.txt

### ISSUE THREAD

**Issue by Permafacture** [jarondl/pygtfs#8]
If you install this module in a virtual environment, and install its dependencies with pip, you can use 

    pip freeze > requirements.txt

Then, we users can install with

    pip install -r requirements.txt

Makes deployment easier.

**Comment by jarondl** [comment]
Hi @Permafacture 
I don't think a `requirements.txt` file is necessary in this case. `pip` will gladly install the dependencies for you without one. You can install from PyPI with

    pip install pygtfs

or from a local folder with

    pip install -e .

And it will find and install the dependencies.

See also:
https://caremad.io/2013/07/setup-vs-requirement/
http://python-packaging-user-guide.readthedocs.org/en/latest/requirements/#requirements-files
